---
title: "README"
output: html_document
---

The data is downloaded from https://zenodo.org/records/8353480 and is of the study: "Killer whale acoustic patterns respond to prey abundance and environmental variability around the Prince Edward Islands, Southern Ocean" by Fannie Shabangu et al. (2023)

Killer whales are apex predators with temporally and spatially varying distributions throughout the world’s oceans. Their ecology and behaviour are poorly understood in most regions due to limited research, often because of logistical challenges. Here, we use easily deployable year-round passive acoustic monitoring device to investigate the seasonal acoustic occurrence and diel vocalizing behaviour of killer whales around the remote sub-Antarctic Prince Edward Islands (PEIs), Southern Ocean. Killer whales showed diel vocalizing patterns that varied seasonally in relation to their prey abundance and social activities. Killer whale calls were intermittently detected year-round with a high number of hours containing calls in October through December, and a secondary peak in March through May, which corresponded to the abundance of seal prey. Random forest modelling identified wind speed as an important predictor of the occurrence of killer whale calls whilst sea surface height, chlorophyll-a, and sea surface temperature were moderately important. We provide the first acoustic evidence that killer whale occurrence around PEIs coincide with variability in environmental conditions and prey abundance. Our results provide the first indication of diel vocalizing pattern of killer whales in the Southern Ocean. This knowledge is important for understanding killer whale ecology and adaptation to the changing oceans.